### ISSUE TITLE
fseek/fgetc error in nextcloud logging

### ISSUE THREAD

**Issue by oksiquatzel** [nextcloud/logreader#34]
Hello,

i upgraded from nextcloud-10.0.01 to nextcloud-11 today and noticed the following error messages in nextcloud log

-----------
{PHP} fseek() expects parameter 1 to be resource, boolean given at nextcloud-11.0.0/apps/logreader/log/logiterator.php#81
{PHP} fgetc() expects parameter 1 to be resource, boolean given at nextcloud-11.0.0/apps/logreader/log/logiterator.php#82
-----------

This Error happens when i click the Logging Submenü in the Administration Section.
It could only be stopped by restarting Webserver. (Browser closing doesn't help)

My System is:
Debian 8.6
Apache 2.4.10
php 5.6.29 apache-module

My Config Entries for Logging are the following:
  'log_type' => 'syslog',
  'logfile' => '',
  'loglevel' => 0,
  'logdateformat' => 'F d, Y H:i:s',
  'logtimezone' => 'Europe/Berlin',
  'log_query' => false,
  'log_authfailip' => false,
  'log_rotate_size' => false,

This Errors is repeated many thousend times a Second in my syslog.
It has produced 95.614.622 Lines within a few minutes.

**Comment by icewind1991** [comment]
Looks like it can't open the logfile (data/nextcloud.log), are you using the builtin logging mechanism?. I've fixed it so it aborts early when it detects it so it doesn't spam the log

**Comment by oksiquatzel** [comment]
Hi,
thans for the fast answer.

i'm using the builtin syslog logging mechanism. As seen in my config above.
I've looked a little into that problem, 
and maybe found a problem in the LogController class in logcontroller.php
The function getLogIterator checks only if the class exists, but not if the file exists.
Maybe there should be first called
$logClass::init();
befor
$handle = fopen($logClass::getLogFilePath(), 'rb');
because the logFile may be not set in $logClass

after that checking if $handle is a real $handle
because when i set log_file to /var/log/syslog in my config the
file exists but is not readable for my webuser

Thanks

**Comment by greg0r** [comment]
Hi guys,
just updated from 11.0.1 to 11.0.2. Still have the same issue with syslog logging. Very annoying because i have to delete my 15GB syslog file as there is no way in a decent amount of time to extract the important entries. And my Backup will not be happy about it.

**Comment by crequill** [comment]
Hi, Same problem here. On archlinux with nextcloud 11.0.2 with syslog logging. To stop it you have just to restart http. Please open this issue again.

**Comment by Mehlstaub** [comment]
Same Problem here. Ubuntu 16.04

**Comment by js94x** [comment]
Same Problem here. config.php:
` 'log_type' => 'syslog',
  'syslog_tag' => 'Nextcloud_test',
`

Seems the official Nextcloud 11.0.2 tarball/zip doesn´t include this commit:
wget -O /tmp/logcontroller.php https://raw.githubusercontent.com/nextcloud/logreader/stable11/lib/Controller/LogController.php
wget -O /tmp/nextcloud.zip  https://download.nextcloud.com/server/releases/nextcloud-11.0.2.zip

unzip /tmp/nextcloud.zip
diff /tmp/nextcloud/apps/logreader/controller/logcontroller.php /tmp/logcontroller.php
51c51
<               $dateFormat = $this->config->getSystemValue('logdateformat', \DateTime::ISO8601);
---
>               $dateFormat = $this->config->getSystemValue('logdateformat', \DateTime::ATOM);
56c56,60
<                               return new LogIterator($handle, $dateFormat);
---
>                               if ($handle) {
>                                       return new LogIterator($handle, $dateFormat);
>                               } else {
>                                       throw new \Exception("Error while opening ".$logClass::getLogFilePath());
>                               }
76a81,82
>        *
>        * @NoCSRFRequired
79a86,87
>               $iterator = new \LimitIterator($iterator, 0, 100000); // limit the number of message we search to avoid huge search times
>               $iterator->rewind();
80a89
>               $iterator->rewind();

To solve the problem I replaced logcontroller.php with that one from GitHub.

**Comment by icewind1991** [comment]
The fix should also be released with the upcoming 11.0.3
